// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vcolor.cpp"
#include "Vcolor___024root__DepSet_he88bcea7__0.cpp"
#include "Vcolor___024root__DepSet_h2e97acaa__0.cpp"
#include "Vcolor__Trace__0.cpp"
#include "Vcolor___024root__Slow.cpp"
#include "Vcolor___024root__DepSet_he88bcea7__0__Slow.cpp"
#include "Vcolor___024root__DepSet_h2e97acaa__0__Slow.cpp"
#include "Vcolor___024unit__Slow.cpp"
#include "Vcolor___024unit__DepSet_h9eab786c__0__Slow.cpp"
#include "Vcolor__Syms.cpp"
#include "Vcolor__Trace__0__Slow.cpp"
